v 1.10.0

diff --git a/src/wine-update b/src/wine-update
--- a/src/wine-update
+++ b/src/wine-update
@@ -4,18 +4,42 @@ repo="https://dl.winehq.org/wine-builds/debian/pool/main/"
 dir="/opt/"
 release=$(lsb_release -cs)
 
-. ./libs/wine_helper_global.shlib
+. /usr/local/lib/wine_helper/wine_helper_global.shlib
 [ -f $conf ] && . $conf
 
 wine_ver_get=$(ls $dir | sort --version-sort | sed '/wine/!d;$!d') # get the lasted version of wine in dir, e.g. wine_1.8.0
 wine_path=$dir$wine_ver_get"/bin/"
 
+fetchMachine()
+{
+	local mach=$(uname -m)
+	if [ "$mach" = "armv6l" ] || [ "$mach" = "armv7l" ] || [ "$mach" = "ppc" ] || [ "$mach" = "ppc64" ] || [ "$mach" = "mips" ] || [ "$mach" = "sparc64" ]; then
+		echo "arm\ppc\mips\sparc machines are not supporting. Please, use your distribution repository or build wine for yourself."
+		exit 1
+	fi
+}
+
+fetchSystem()
+{	
+	local sys=$(uname -s)
+	
+	if [ $(sys) = "GNU" ]; then
+		echo "Hurd is not supported."
+		exit 1
+	elif [ $(sys) = "SunOS" ]; then
+		echo "Solaris\OpenIndiana\SmartOS is not supported."
+		exit 1
+	fi
+	
+	echo $sys | awk '{print tolower($0)}'
+}
+
 # https://www.playonlinux.com/wine/binaries/
 # both 32x and 64x
 getPOLWine()
 {
-		if [ ! -z "$1" ] || [ ! -z "$2" ]; then
-			echo "Error getting Play On Linux wine binaries. First or second parametrs is empty. Must be: $0 amd64 wine-1.5.26"
+		if [ -z "$1" ] || [ -z "$1" ]; then
+			echo "Error getting Play On Linux wine binaries. First or second parametrs is empty. Must be: $0 wine-1.5.26 [amd64]"
 		fi
 	
 		GET="https://www.playonlinux.com/wine/binaries/linux-"$1"/"PlayOnLinux-$2-linux-$1".pol"
@@ -55,7 +79,7 @@ getStagingWine()
 	tmp_dir="/tmp/wine-staging/"
 	mkdir $tmp_dir
 	
-	if [ `uname -m` == "x86_64" ]; then
+	if [ "$mach" = "x86_64" ] || [ "$mach" = "k1om" ]; then
 		echo "Script detected, that your system is amd64, so downloading 64bit wine."
 		echo "Downloading and extracting wine..."
 		# getting wine itself
@@ -117,7 +141,8 @@ elif [ "$1" = "pol" ]; then
 	die
 	getPOLWine "$2" "$3"
 else
-	askStagingWine
+	fetchSystem
+	#askStagingWine
 fi
 
 [ -f "/tmp/wine-staging.html" ] && rm /tmp/wine-staging.html
